Fix docs for pre-commit hook of DjCSS
rtts/djhtml pull request #55
Opened 2022-02-07 14:51 UTC by DmytroLitvinov

Hi there,
I have a project with .css and .scss files. I followed the README.md and found out that it does not work for me.
When I integrated it, It showed me:
> DjCSS................................................(no files to check)Skipped

According to docs,
![Selection_1220](https://user-images.githubusercontent.com/16066485/152811891-2337fcc5-7f20-478c-96db-8028ed9fffea.png)

We see that it should be `types_or` for `OR` filtering. File should be `CSS` **OR** `SCSS`

2022-02-07 14:55 UTC, DmytroLitvinov commented
Ping @JaapJoris.

2022-02-07 15:29 UTC, JaapJoris requested changes
Thank you for the improvement of the documentation! This was indeed quite an oversight of me. For the purpose of keeping the documentation simple, I have suggested one improvement. Could you verify that it works with my suggestion and, if so, could you push that as a change?

2022-02-07 15:29 UTC, JaapJoris commented on README.md
> +      types_or: [css, scss]
Does it also work with just the following?

```
    - id: djcss
      # Run this hook on both CSS and SCSS files
      types_or: [scss]
```

Because that would be a lot neater, documentation-wise

2022-02-07 15:46 UTC, DmytroLitvinov commented on README.md
> +      types_or: [css, scss]
No, it does not work.
![Selection_1221](https://user-images.githubusercontent.com/16066485/152821789-130981fc-b592-464a-abcb-e789b58741e5.png)

2022-02-07 17:27 UTC, JaapJoris commented on README.md
> +      types_or: [css, scss]
In that case, I would prefer not adding this improvement to the documentation, but to the actual hook instead, so indenting both CSS and SCSS will be the default for everyone \o/

I've pushed a commit to accomplish this. Do you approve?

2022-02-07 20:14 UTC, DmytroLitvinov commented on README.md
> +      types_or: [css, scss]
@JaapJoris , sure.
Thanks for quick reaction :+1:

2022-02-07 20:15 UTC, DmytroLitvinov commented on README.md
> +      types_or: [css, scss]
Will be waiting for new release with fix.

2022-02-08 09:31 UTC, JaapJoris approved these changes

2022-02-08 09:32 UTC, merged

2022-02-08 09:39 UTC, JaapJoris commented on README.md
> +      types_or: [css, scss]
Thank you again for helping out! Feel free to open more PRs in the future! The improved `djcss` hook has now been released: https://github.com/rtts/djhtml/releases/tag/v1.4.14